export const EVENT_LIST_REQUEST = 'EVENT_LIST_REQUEST';
export const EVENT_LIST_SUCCESS = 'EVENT_LIST_SUCCESS';
export const EVENT_LIST_FAIL = 'EVENT_LIST_FAIL';

export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUEST';
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS';
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL';

export const USER_EVENTS_REQUEST = 'USER_EVENTS_REQUEST';
export const USER_EVENTS_SUCCESS = 'USER_EVENTS_SUCCESS';
export const USER_EVENTS_FAIL = 'USER_EVENTS_FAIL';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

export const USER_REGISTRATION_REQUEST = 'USER_REGISTRATION_REQUEST';
export const USER_REGISTRATION_SUCCESS = 'USER_REGISTRATION_SUCCESS';
export const USER_REGISTRATION_FAIL = 'USER_REGISTRATION_FAIL';

export const USER_CART_REQUEST = 'USER_CART_REQUEST';
export const USER_CART_SUCCESS = 'USER_CART_SUCCESS';
export const USER_CART_FAIL = 'USER_CART_FAIL';
export const USER_CART_RESET = 'USER_CART_RESET';

export const USER_CART_ADD_REQUEST = 'USER_CART_ADD_REQUEST';
export const USER_CART_ADD_SUCCESS = 'USER_CART_ADD_SUCCESS';
export const USER_CART_ADD_FAIL = 'USER_CART_ADD_FAIL';

export const USER_CART_REMOVE_REQUEST = 'USER_CART_REMOVE_REQUEST';
export const USER_CART_REMOVE_SUCCESS = 'USER_CART_REMOVE_SUCCESS';
export const USER_CART_REMOVE_FAIL = 'USER_CART_REMOVE_FAIL';

export const USER_CONFIRMATION_REQUEST = 'USER_CONFIRMATION_REQUEST';
export const USER_CONFIRMATION_SUCCESS = 'USER_CONFIRMATION_SUCCESS';
export const USER_CONFIRMATION_FAIL = 'USER_CONFIRMATION_FAIL';
export const USER_CONFIRMATION_RESET = 'USER_CONFIRMATION_RESET';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PROMO_REQUEST = 'ORDER_PROMO_REQUEST';
export const ORDER_PROMO_SUCCESS = 'ORDER_PROMO_SUCCESS';
export const ORDER_PROMO_FAIL = 'ORDER_PROMO_FAIL';

export const USER_ORDERS_REQUEST = 'USER_ORDERS_REQUEST';
export const USER_ORDERS_SUCCESS = 'USER_ORDERS_SUCCESS';
export const USER_ORDERS_FAIL = 'USER_ORDERS_FAIL';

export const USER_TICKETS_REQUEST = 'USER_TICKETS_REQUEST';
export const USER_TICKETS_SUCCESS = 'USER_TICKETS_SUCCESS';
export const USER_TICKETS_FAIL = 'USER_TICKETS_FAIL';

export const TICKET_DETAILS_REQUEST = 'TICKET_DETAILS_REQUEST';
export const TICKET_DETAILS_SUCCESS = 'TICKET_DETAILS_SUCCESS';
export const TICKET_DETAILS_FAIL = 'TICKET_DETAILS_FAIL';

export const PUBLIC_TICKET_DETAILS_REQUEST = 'PUBLIC_TICKET_DETAILS_REQUEST';
export const PUBLIC_TICKET_DETAILS_SUCCESS = 'PUBLIC_TICKET_DETAILS_SUCCESS';
export const PUBLIC_TICKET_DETAILS_FAIL = 'PUBLIC_TICKET_DETAILS_FAIL';
